a bit more specific test to avoid false postives
git-svn-id: http://svn.zentyal.org/zentyal/trunk@13559 866bc4c1-54da-0310-a958-9d5a9a0e8d04

diff --git a/extra/anste/tests/proxy/basic/test-filter-deny/test b/extra/anste/tests/proxy/basic/test-filter-deny/test
--- a/extra/anste/tests/proxy/basic/test-filter-deny/test
+++ b/extra/anste/tests/proxy/basic/test-filter-deny/test
@@ -1,36 +1,88 @@
-#!/bin/bash
+#!/usr/bin/perl
+use strict;
+use warnings;
 
-PROXY="192.168.2.1:3128"
+my $HOST     = $ENV{HOST};
+my $USERNAME = $ENV{USERNAME};
+my $PASSWORD = $ENV{PASSWORD};
+my $LOOK_FOR = $ENV{LOOK_FOR};
 
-if [ "x$PASSWORD" != "x" ]
-then
-    export http_proxy="http://$USERNAME:$PASSWORD@$PROXY/"
-else
-    export http_proxy="http://$PROXY/"
-fi
-echo "Using http_proxy=$http_proxy ..."
+defined $HOST or
+    die "Missing environment variable: HOST";
+defined $LOOK_FOR or
+    die "Missing environment variable: LOOK_FOR";
 
-for i in `seq 1 10`
-do
-    [ -f output.html ] && rm output.html
+my @lookups = split 'AND', $LOOK_FOR;
 
-    echo "HTTP request to $HOST"
-    wget -t 3 $HOST -O output.html > wget_output 2>&1
 
-    echo "wget output:"
-    cat wget_output
+my $PROXY="192.168.2.1:3128";
+my $url;
+if ($PASSWORD) {
+    $url = "http://$USERNAME:$PASSWORD" . '@' . "$PROXY/";
+} else {
+    $url = "http://$PROXY/";
+}
 
-    echo "Checking if access was denied"
-    grep "Access has been Denied" output.html
+my $outputFile = 'output.html';
 
-    if [ $? = 0 ]
-    then
-        echo "Access denied."
-        exit 0
-    else
-        sleep 2
-    fi
-done
+print "Using http_proxy=$url ...\n";
 
-echo "Test failed (timeout)."
-exit 1
+for (1 .. 10) {
+    if (-f $outputFile) {
+        system "rm $outputFile";
+        $? != 0 and die $!;
+    }
+
+    print "HTTP request to $HOST\n";
+    my $wgetCmd = "http_proxy=\"$url\" wget -t 3 $HOST -O $outputFile 2>&1";
+    print "wget command: $wgetCmd\n";
+    my @wgetOutput = `$wgetCmd`;
+
+    print "wget output: @wgetOutput\n";
+
+    my @htmlOutput = `cat $outputFile`;
+    print "Retrieved page:\n\n@htmlOutput\n";
+
+    print "Checking if access was denied";
+    my $denied = grep {
+        m/Access Denied/;
+    } @htmlOutput;
+
+    if (not $denied) {
+        sleep 2;
+        next;
+    }
+
+    print "Access denied.\n";
+
+    my $success =  1;
+    foreach my $lookup (@lookups) {
+        my $found = grep {
+            m/$lookup/
+        } @htmlOutput;
+        
+        if (not $found) {
+            $success = 0;
+            last;
+        }
+    }
+ 
+
+    if ($success) {
+        print "FOUND: $LOOK_FOR\n";
+        exit 0;
+    } else {
+        print "NOT FOUND: $LOOK_FOR\n";
+
+        exit 1;
+        
+    }
+
+}
+
+
+
+print "Test failed (timeout).\n";
+exit 1;
+
+1;
