Update release-upgrade script for 6.0

diff --git a/main/core/src/scripts/release-upgrade b/main/core/src/scripts/release-upgrade
--- a/main/core/src/scripts/release-upgrade
+++ b/main/core/src/scripts/release-upgrade
@@ -1,5 +1,30 @@
 #!/bin/bash
 
+# Preliminary checks
+
+if [ $(df /boot | tail -1 | awk '{print $4}') -lt 51200 ];
+then
+    echo "Upgrade cannot be performed due to low disk space (less than 50MB available on /boot)"
+    exit 2
+fi
+
+for i in / /var
+do
+    if [ `df $i | tail -1 | awk '{print $4}'` -lt 358400 ];
+    then
+        echo -e "Upgrade cannot be performed due to low disk space (less than 350MB available on $i)"
+        exit 2
+    fi
+done
+
+SOURCES=/etc/apt/sources.list
+if ! grep -v "^#" $SOURCES | grep -q "ubuntu.com"
+then
+    echo "deb http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse" >> $SOURCES
+    echo "deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse" >> $SOURCES
+    echo "deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse" >> $SOURCES
+fi
+
 UPGRADE_FILE=/var/lib/zentyal/.upgrade-finished
 
 rm -f $UPGRADE_FILE
@@ -12,7 +37,7 @@ function upgrade
 
     for i in `seq 1 10`
     do
-        if apt-get dist-upgrade -y --force-yes --download-only
+        if apt-get dist-upgrade -y --download-only
         then
             break
         else
@@ -21,7 +46,7 @@ function upgrade
         fi
     done
 
-    apt-get dist-upgrade --purge -y --force-yes -o DPkg::Options::="--force-confdef"
+    apt-get dist-upgrade -y -o DPkg::Options::="--force-overwrite" -o DPkg::Options::="--force-confdef"
 }
 
 sed -i "s/^deb-src/#deb-src/g" /etc/apt/sources.list
@@ -29,25 +54,36 @@ sed -i "s/^deb-src/#deb-src/g" /etc/apt/sources.list
 echo; echo "Upgrading your current system to the latest packages..."; echo
 upgrade
 
-echo; echo "Upgrading from Zentyal 4.1 to Zentyal 4.2..."; echo
-sed -ri '/zentyal(.)4.1/d' /etc/apt/sources.list
-echo 'deb http://archive.zentyal.org/zentyal 4.2 main extra' > /etc/apt/sources.list.d/zentyal-archive.list
-sed -i 's/zentyal-qa-4.1/zentyal-qa-4.2/g' /etc/apt/sources.list.d/zentyal-qa.list
-# Workaround to avoid dependency problems when packages are hold
-for e in `grep -R "a=zentyal-qa" /etc/apt | cut -f1 -d:`; do rm -f $e; done
+echo; echo "Upgrading from Ubuntu 16.04 to 18.04 with Zentyal 5.0..."; echo
+sed -i 's/xenial/bionic/g' /etc/apt/sources.list
+sed -ri '/zentyal(.)5.1/d' /etc/apt/sources.list
+echo 'deb http://archive.zentyal.org/zentyal 6.0 main' > /etc/apt/sources.list.d/zentyal-archive.list
+sed -i 's/zentyal-qa 5.1/zentyal-qa 6.0/g' /etc/apt/sources.list.d/zentyal-qa.list
+
+# workaround redis crash during dist-upgrade
+apt-get update
+cp /etc/redis/redis.conf /etc/redis/redis.conf.bak
+apt-get install -y -o DPkg::Options::="--force-confnew" redis-server
+sed -i 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf
+dpkg --configure -a
+systemctl restart redis-server
 
 upgrade
 
-if apt-get dist-upgrade --purge -y --force-yes -o DPkg::Options::="--force-confdef"
+# workaround ejabberd upgrade
+rm -f /var/lib/dpkg/info/ejabberd.postinst
+
+if dpkg --configure -a --force-confdef
 then
     # Purge all no longer needed running services
     dpkg -l | grep 'zentyal-' | cut -d' ' -f3 | xargs apt-mark manual
-    apt-get autoremove --purge -y --force-yes -o DPkg::Options::="--force-confdef"
+    apt-get autoremove --purge -y -o DPkg::Options::="--force-confdef"
 
-    # Restart Zentyal UI
-    zs webadmin restart
+    apt-get -f install -y -o DPkg::Options::="--force-confdef"
 
-    echo; echo "Zentyal upgrade finished!"
+    dpkg --configure -a --force-confdef
+
+    echo; echo "Zentyal upgrade finished! Please restart your server now."
 else
     echo; echo "Zentyal upgrade failed. Full log at /var/log/zentyal/upgrade.log."
 fi
