add release upgrade code (available to update from 6.0 to 6.1)

diff --git a/main/core/src/scripts/release-upgrade b/main/core/src/scripts/release-upgrade
--- a/main/core/src/scripts/release-upgrade
+++ b/main/core/src/scripts/release-upgrade
@@ -1,10 +1,131 @@
 #!/bin/bash
 
+SOURCES=/etc/apt/sources.list
 UPGRADE_FILE=/var/lib/zentyal/.upgrade-finished
+TMPFILE=/tmp/packages-list
+QALIST=/etc/apt/sources.list.d/zentyal-qa.list
 
-rm -f $UPGRADE_FILE
+DESTMAJOR=6
+DESTMINOR=1
+CURMAJORV=`dpkg -l|grep zentyal-core | awk '{print $3}' | cut -d'.' -f1`
+CURMINORV=`dpkg -l|grep zentyal-core | awk '{print $3}' | cut -d'.' -f2`
 
-export DEBIAN_FRONTEND=noninteractive
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+NC='\033[0m'
+BOLD=$(tput bold)
+NORM=$(tput sgr0)
+
+function checkZentyalVersion
+{
+    echo -e "${GREEN} - Checking the zentyal-core version...${NC}" 
+    if [ $CURMAJORV -gt $DESTMAJOR ]; 
+    then
+        echo -e "${RED}${BOLD} Your system is up to date${NC}${NORM}" 
+        exit 1
+    else
+        if [ $CURMINORV -gt $DESTMINOR ] || [ $CURMINORV -eq $DESTMINOR ];
+        then
+            echo -e "${RED}${BOLD} Your system is up to date${NC}${NORM}" 
+            exit 1
+        fi
+    fi
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
+
+function checkDiskSpace
+{
+    echo -e "${GREEN} - Checking for available disk space...${NC}"
+    if [ $(df /boot | tail -1 | awk '{print $4}') -lt 51200 ];
+    then
+        echo "${RED}  Upgrade cannot be performed due to low disk space (less than 50MB available on /boot)${NC}"
+        exit 2
+    fi
+
+    for i in / /var
+    do
+        if [ `df $i | tail -1 | awk '{print $4}'` -lt 358400 ];
+        then
+            echo -e "${RED}  Upgrade cannot be performed due to low disk space (less than 350MB available on $i)${NC}"
+            exit 2
+        fi
+    done
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
+
+function checkUbuntuReposotories
+{
+    echo -e "${GREEN} - Checking and setting ubuntu repositories...${NC}"
+    if ! grep -v "^#" $SOURCES | grep -q "ubuntu.com"
+    then
+        echo "deb http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse" >> $SOURCES
+        echo "deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse" >> $SOURCES
+        echo "deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse" >> $SOURCES        
+    fi
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
+
+function checkBrokenPackages
+{
+    echo -e "${GREEN} - Installed Zentyal packages:${NC}"
+    dpkg -l | grep 'zentyal-'
+    echo;
+    echo -e "${GREEN} - Checking for broken packages...${NC}"
+    touch $TMPFILE && dpkg -l | awk '{ if ( NR > 5  ) { print } }' > $TMPFILE
+    if grep -vE '^ii' $TMPFILE
+    then
+        echo -e "${RED}  You have broken packages, please, try to execute dpkg --configure -a before to continue${NC}"
+        exit 1
+    fi  
+    rm -f $TMPFILE
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
+
+function checkGPG
+{
+    echo -e "${GREEN} - Looking for gnupg package...${NC}"
+    dpkg -s gnupg &> /dev/null
+    if [ $? -eq 0 ]; 
+    then
+        echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+    else
+        echo -e "${RED}  Package is NOT installed! Trying to install it...${NC}";echo
+        apt-get install gnupg -y
+    fi
+}
+
+function checkZentyalMySQL
+{
+    echo -e "${GREEN} - Checking Zentyal's MySQL db...${NC}"
+    mysqlcheck --databases zentyal
+    echo;
+}
+
+function cleanPreviousUpgrade
+{
+    echo -e "${GREEN} - Cleaning $UPGRADE_FILE if exists...${NC}"
+    if [ -f $UPGRADE_FILE ]
+    then
+        rm -f $UPGRADE_FILE
+    fi
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
+
+function prepareUpgrade
+{
+    checkZentyalVersion
+    checkDiskSpace
+    checkUbuntuReposotories
+    checkBrokenPackages
+    checkGPG
+    checkZentyalMySQL
+    cleanPreviousUpgrade
+
+    export DEBIAN_FRONTEND=noninteractive
+    sed -i "s/^deb-src/#deb-src/g" /etc/apt/sources.list
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
 
 function upgrade
 {
@@ -12,44 +133,130 @@ function upgrade
 
     for i in `seq 1 10`
     do
-        if apt-get dist-upgrade -y --force-yes --download-only
+        if apt-get dist-upgrade -y --download-only
         then
             break
         else
-            echo "Download failed, retrying in 5 seconds..."
+            echo -e "${RED}  Download failed, retrying in 5 seconds...${NC}"
             sleep 5
         fi
     done
 
-    apt-get dist-upgrade --purge -y --force-yes -o DPkg::Options::="--force-confdef"
+    apt-get dist-upgrade -y -o DPkg::Options::="--force-overwrite" -o DPkg::Options::="--force-confdef"
+
+    checkBrokenPackages
 }
 
-sed -i "s/^deb-src/#deb-src/g" /etc/apt/sources.list
+function prepareZentyalRepositories
+{
+    wget -qO - keys.zentyal.org/zentyal-6.1-packages.asc | sudo apt-key add -
 
-echo; echo "Upgrading your current system to the latest packages..."; echo
+    sed -ri '/zentyal(.)6.0/d' /etc/apt/sources.list
+    echo 'deb http://packages.zentyal.org/zentyal 6.1 main extra' > /etc/apt/sources.list.d/zentyal-packages.list
+
+    if [ -f '/etc/apt/sources.list.d/zentyal-archive.list' ];
+    then
+        rm -f /etc/apt/sources.list.d/zentyal-archive.list
+    fi 
+
+    if [ -f $QALIST ];
+    then
+        sed -i 's/archive/packages/g' $QALIST
+        sed -i 's/zentyal-qa 6.0/zentyal-qa 6.1/g' $QALIST
+    fi
+    
+    apt-get update
+}
+
+function configureRedis
+{
+    cp /etc/redis/redis.conf /etc/redis/redis.conf.bak
+    apt-get install -y -o DPkg::Options::="--force-confnew" redis-server
+    sed -i 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf
+    dpkg --configure -a
+    systemctl restart redis-server
+}
+
+function eJabberdUpgrade
+{
+    # https://docs.ejabberd.im/admin/upgrade/
+    EJABBERD_NODE=$(grep "the database is owned by" /var/log/ejabberd/error.log |tail -1 | sed "s/'//"|rev|cut -d[ -f1|rev|cut -d] -f1)
+    if [ -z "$EJABBERD_NODE" ]
+    then
+        EJABBERD_NODE="ejabberd@$HOSTNAME"
+    fi
+    echo "ERLANG_NODE=$EJABBERD_NODE" >> /etc/ejabberd/ejabberdctl.cfg
+}
+
+function getCVDs
+{
+    if [ -d /var/lib/clamav ] && ! [ -f /var/lib/clamav/main.cvd ]
+    then
+        freshclam
+        zs antivirus restart
+    fi
+}
+
+function postCheckPackages
+{
+    echo;echo;echo -e "${GREEN} - Installed Zentyal packages:${NC}"
+    dpkg -l | grep 'zentyal-'
+    touch $TMPFILE && dpkg -l | awk '{ if ( NR > 5  ) { print } }' > $TMPFILE
+    if grep -vE '^(ii|rc)' $TMPFILE
+    then
+        echo -e "${RED}  You have broken packages, please, try to execute dpkg --configure -a before to continue${NC}"
+        exit 1
+    fi  
+    rm -f $TMPFILE
+    echo -e "${GREEN}${BOLD}...OK${NC}${NORM}";echo
+}
+
+echo; echo -e "${YELLOW}*** Preparing your system for the upgrade...${NC}"; echo
+prepareUpgrade
+
+echo; echo -e "${YELLOW}*** Upgrading your current system to the latest packages...${NC}"; echo
 upgrade
 
-echo; echo "Upgrading from Zentyal 4.1 to Zentyal 4.2..."; echo
-sed -ri '/zentyal(.)4.1/d' /etc/apt/sources.list
-echo 'deb http://archive.zentyal.org/zentyal 4.2 main extra' > /etc/apt/sources.list.d/zentyal-archive.list
-sed -i 's/zentyal-qa-4.1/zentyal-qa-4.2/g' /etc/apt/sources.list.d/zentyal-qa.list
-# Workaround to avoid dependency problems when packages are hold
-for e in `grep -R "a=zentyal-qa" /etc/apt | cut -f1 -d:`; do rm -f $e; done
+echo; echo -e "${YELLOW}*** Preparing for upgrade to Zentyal 6.1...${NC}"; echo
+apt-get purge -y ubuntu-minimal # remove unnecessary metapackage to avoid it from being kept back and appear as available update
+prepareZentyalRepositories
+configureRedis # workaround Redis crash during dist-upgrade
 
+echo; echo -e "${YELLOW}*** Upgrading Zentyal from ${CURMAJORV}.${CURMINORV} to ${DESTMAJOR}.${DESTMINOR}...${NC}"; echo
 upgrade
+eJabberdUpgrade # eJabberd upgrade
+getCVDs # update ClamAV Virus Database files
 
-if apt-get dist-upgrade --purge -y --force-yes -o DPkg::Options::="--force-confdef"
+rm -f /var/lib/dpkg/info/spamassassin.postinst
+
+dpkg --configure -a --force-confdef
+
+rm -f /var/lib/dpkg/info/ejabberd.postinst
+
+dpkg --configure -a --force-confdef
+
+apt-get -f install -y -o DPkg::Options::="--force-confdef"
+
+if dpkg --configure -a --force-confdef
 then
+    systemctl disable lxdm
+    systemctl enable zentyal.lxdm
+
     # Purge all no longer needed running services
     dpkg -l | grep 'zentyal-' | cut -d' ' -f3 | xargs apt-mark manual
-    apt-get autoremove --purge -y --force-yes -o DPkg::Options::="--force-confdef"
+    apt-get autoremove --purge -y -o DPkg::Options::="--force-confdef"
 
-    # Restart Zentyal UI
-    zs webadmin restart
+    apt-get -f install -y -o DPkg::Options::="--force-confdef"
 
-    echo; echo "Zentyal upgrade finished!"
+    dpkg --configure -a --force-confdef
+
+    postCheckPackages
+    echo; echo -e "${GREEN}${BOLD}*** Zentyal upgrade finished! Please restart your server now.${NC}${NORM}"
+
+    sleep 2
+    pkill -f upgrade-log-server
 else
-    echo; echo "Zentyal upgrade failed. Full log at /var/log/zentyal/upgrade.log."
+    echo; echo -e "${RED}${BOLD}*** Zentyal upgrade failed. Full log at /var/log/zentyal/upgrade.log.${NC}${NORM}"
 fi
 
 apt-get clean
